using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Text;
using System.Threading;


namespace MewUI.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class MewPropertyIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. 注入 Attribute
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("AsMewPropertyAttribute.g.cs", @"// <auto-generated/>
#nullable enable
namespace System
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public sealed class AsMewPropertyAttribute(object? defaultValue = null) : Attribute
    {
        public object? DefaultValue { get; set; } = defaultValue;
        public global::Aprillz.MewUI.MewPropertyOptions MewPropertyOptions { get; set; }
    }
}
"));

        // 2. 直接收集，不做 Where/Select 链式调用以避免元组字段名丢失
        var properties = context.SyntaxProvider.ForAttributeWithMetadataName(
            "System.AsMewPropertyAttribute",
            predicate: static (node, _) => node is PropertyDeclarationSyntax,
            transform: static (ctx, ct) => ExtractAndGenerate(ctx, ct))
            .Collect(); // 直接收集 Nullable 元组数组

        // 3. 按类分组拼接输出
        context.RegisterSourceOutput(properties, static (spc, items) =>
        {
            if (items.IsDefaultOrEmpty) return;

            // 在 SourceOutput 内部过滤 null，避免管道类型推断问题
            var validItems = items.Where(x => x.HasValue).Select(x => x!.Value);

            foreach (var group in validItems.GroupBy(x => (x.Namespace, x.ClassName)))
            {
                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("#nullable enable");
                sb.AppendLine();

                if (!string.IsNullOrEmpty(group.Key.Namespace))
                    sb.AppendLine($"namespace {group.Key.Namespace};\n");

                sb.AppendLine($"partial class {group.Key.ClassName}\n{{");
                foreach (var item in group)
                    sb.Append(item.Fragment);
                sb.AppendLine("}");

                var hint = string.IsNullOrEmpty(group.Key.Namespace)
                    ? $"{group.Key.ClassName}.MewProperties.g.cs"
                    : $"{group.Key.Namespace}.{group.Key.ClassName}.MewProperties.g.cs";

                spc.AddSource(hint.Replace('.', '_'), sb.ToString());
            }
        });
    }

    /// <summary>
    /// 提取元数据 + 生成代码片段，一步到位
    /// </summary>
    private static (string Namespace, string ClassName, string Fragment)? ExtractAndGenerate(
        GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IPropertySymbol prop)
            return null;

        var type = prop.ContainingType;

        // 检查 partial
        bool isPartial = false;
        foreach (var syntaxRef in type.DeclaringSyntaxReferences)
        {
            if (syntaxRef.GetSyntax(ct) is TypeDeclarationSyntax tds &&
                tds.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                isPartial = true;
                break;
            }
        }
        if (!isPartial) return null;

        // 从 Attribute 读取 DefaultValue
        var attr = ctx.Attributes[0];
        string fqTypeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var defaultValueArg = attr.GetArgumentValue("DefaultValue");

        string defaultVal = defaultValueArg.IsNull
            ? (prop.Type.IsValueType ? $"default({fqTypeName})" : "null")
            : defaultValueArg.ToCSharpString();

        var mewPropertyOptionsArg = attr.GetArgumentValue("MewPropertyOptions");
        string mewPropertyOptions = mewPropertyOptionsArg.IsNull
            ? "global::Aprillz.MewUI.MewPropertyOptions.AffectsRender"
            : mewPropertyOptionsArg.ToCSharpString();

        string typeName = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat
            .WithMiscellaneousOptions(SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier));
        bool hasSetter = prop.SetMethod != null && !prop.SetMethod.IsInitOnly;
        string ns = type.ContainingNamespace?.IsGlobalNamespace == true
            ? ""
            : type.ContainingNamespace?.ToDisplayString() ?? "";
        string className = type.Name;
        string name = prop.Name;

        // 直接构建代码片段
        var sb = new StringBuilder();
        sb.AppendLine($"    /// <inheritdoc cref=\"{name}\"/>");
        sb.AppendLine($"    /// <remarks>{name} property</remarks>");
        sb.AppendLine($"    public static readonly global::Aprillz.MewUI.MewProperty<{typeName}> {name}Property =");
        sb.AppendLine($"        global::Aprillz.MewUI.MewProperty<{typeName}>.Register<{className}>(");
        sb.AppendLine($"            nameof({name}),");
        sb.AppendLine($"            {defaultVal},");
        sb.AppendLine($"            {mewPropertyOptions},");
        sb.AppendLine($"            static (self, old, newValue) => self.On{name}Changed(old, newValue));");
        sb.AppendLine();
        sb.AppendLine($"    /// <inheritdoc cref=\"{name}\"/>");
        sb.AppendLine($"    public partial {typeName} {name}");
        sb.AppendLine("    {");
        sb.AppendLine($"        get => GetValue({name}Property);");
        if (hasSetter)
            sb.AppendLine($"        set => SetValue({name}Property, value);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    /// <inheritdoc cref=\"{name}\"/>");
        sb.AppendLine($"    /// <remarks>{name} changed</remarks>");
        sb.AppendLine($"    partial void On{name}Changed({typeName} oldValue, {typeName} newValue);");
        sb.AppendLine();

        return (ns, className, sb.ToString());
    }
}